print("----------------")
print("Choose language:")
print("----------------")
print("1. English - USA")
print("2. English - United Kingdom")
print("3. Русский - Россия")
print("----------------")
language=str(input("Enter number of your language: "))
print("----------------")
if language=="1":
    print("Choose mathematical operation:")
    print("----------------")
    print("1. +")
    print("2. -")
    print("3. *")
    print("4. /")
    print("----------------")
    operation=str(input("Enter number of mathematical operation: "))
    print("----------------")
    if operation=="1":
        first=int(input("Enter first number: "))
        second = int(input("Enter second number: "))
        print("----------------")
        print("Answer:",first+second)
    if operation=="2":
        first=int(input("Enter first number: "))
        second = int(input("Enter second number: "))
        print("----------------")
        print("Answer:",first-second)
    if operation=="3":
        first=int(input("Enter first number: "))
        second = int(input("Enter second number: "))
        print("----------------")
        print("Answer:",first*second)
    if operation=="4":
        first=int(input("Enter first number: "))
        second = int(input("Enter second number: "))
        print("----------------")
        print("Answer:",first/second)
    print("----------------")
    input("Press ( Enter ) for exit.")
if language=="2":
    print("Choose mathematical operation:")
    print("----------------")
    print("1. +")
    print("2. -")
    print("3. *")
    print("4. /")
    print("----------------")
    operation=str(input("Enter number of mathematical operation: "))
    print("----------------")
    if operation=="1":
        first=int(input("Enter first number: "))
        second = int(input("Enter second number: "))
        print("----------------")
        print("Answer:",first+second)
    if operation=="2":
        first=int(input("Enter first number: "))
        second = int(input("Enter second number: "))
        print("----------------")
        print("Answer:",first-second)
    if operation=="3":
        first=int(input("Enter first number: "))
        second = int(input("Enter second number: "))
        print("----------------")
        print("Answer:",first*second)
    if operation=="4":
        first=int(input("Enter first number: "))
        second = int(input("Enter second number: "))
        print("----------------")
        print("Answer:",first/second)
    print("----------------")
    input("Press ( Enter ) for exit.")
if language=="3":
    print("Выберите математическую операцию:")
    print("----------------")
    print("1. +")
    print("2. -")
    print("3. *")
    print("4. /")
    print("----------------")
    operation=str(input("Напишите номер математической операции: "))
    print("----------------")
    if operation=="1":
        first=int(input("Напишите первое число: "))
        second = int(input("Напишите второе число: "))
        print("----------------")
        print("Ответ:",first+second)
    if operation=="2":
        first=int(input("Напишите первое число: "))
        second = int(input("Напишите второе число: "))
        print("----------------")
        print("Ответ:",first-second)
    if operation=="3":
        first=int(input("Напишите первое число: "))
        second = int(input("Напишите второе число: "))
        print("----------------")
        print("Ответ:",first*second)
    if operation=="4":
        first=int(input("Напишите первое число: "))
        second = int(input("Напишите второе число: "))
        print("----------------")
        print("Ответ:",first/second)
    print("----------------")
    input("Нажмите ( Enter ) чтобы закрыть.")